# Generated by Django 5.2.4 on 2025-07-06 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=209)),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Action"),
                            ("adventure", "Adventure"),
                            ("animation", "Animation"),
                            ("biography", "Biography"),
                            ("comedy", "Comedy"),
                            ("crime", "Crime"),
                            ("documentary", "Documentary"),
                            ("drama", "Drama"),
                            ("family", "Family"),
                            ("fantasy", "Fantasy"),
                            ("history", "History"),
                            ("horror", "Horror"),
                            ("music", "Music"),
                            ("musical", "Musical"),
                            ("mystery", "Mystery"),
                            ("romance", "Romance"),
                            ("sci-fi", "Science Fiction"),
                            ("sport", "Sport"),
                            ("thriller", "Thriller"),
                            ("war", "War"),
                            ("western", "Western"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "isbn",
                    models.CharField(max_length=13, unique=True, verbose_name="ISBN"),
                ),
                ("publication_date", models.DateField()),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
